// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.6
// source: drama.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DramaMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title    string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author   string `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Category string `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
}

func (x *DramaMessage) Reset() {
	*x = DramaMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drama_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DramaMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DramaMessage) ProtoMessage() {}

func (x *DramaMessage) ProtoReflect() protoreflect.Message {
	mi := &file_drama_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DramaMessage.ProtoReflect.Descriptor instead.
func (*DramaMessage) Descriptor() ([]byte, []int) {
	return file_drama_proto_rawDescGZIP(), []int{0}
}

func (x *DramaMessage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DramaMessage) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DramaMessage) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *DramaMessage) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type CreateDramaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title    string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Author   string `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Category string `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
}

func (x *CreateDramaRequest) Reset() {
	*x = CreateDramaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drama_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDramaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDramaRequest) ProtoMessage() {}

func (x *CreateDramaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drama_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDramaRequest.ProtoReflect.Descriptor instead.
func (*CreateDramaRequest) Descriptor() ([]byte, []int) {
	return file_drama_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDramaRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateDramaRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *CreateDramaRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type CreateDramaReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Drama *DramaMessage `protobuf:"bytes,1,opt,name=drama,proto3" json:"drama,omitempty"`
}

func (x *CreateDramaReply) Reset() {
	*x = CreateDramaReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drama_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDramaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDramaReply) ProtoMessage() {}

func (x *CreateDramaReply) ProtoReflect() protoreflect.Message {
	mi := &file_drama_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDramaReply.ProtoReflect.Descriptor instead.
func (*CreateDramaReply) Descriptor() ([]byte, []int) {
	return file_drama_proto_rawDescGZIP(), []int{2}
}

func (x *CreateDramaReply) GetDrama() *DramaMessage {
	if x != nil {
		return x.Drama
	}
	return nil
}

type UpdateDramaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateDramaRequest) Reset() {
	*x = UpdateDramaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drama_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDramaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDramaRequest) ProtoMessage() {}

func (x *UpdateDramaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drama_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDramaRequest.ProtoReflect.Descriptor instead.
func (*UpdateDramaRequest) Descriptor() ([]byte, []int) {
	return file_drama_proto_rawDescGZIP(), []int{3}
}

type UpdateDramaReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateDramaReply) Reset() {
	*x = UpdateDramaReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drama_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDramaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDramaReply) ProtoMessage() {}

func (x *UpdateDramaReply) ProtoReflect() protoreflect.Message {
	mi := &file_drama_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDramaReply.ProtoReflect.Descriptor instead.
func (*UpdateDramaReply) Descriptor() ([]byte, []int) {
	return file_drama_proto_rawDescGZIP(), []int{4}
}

type DeleteDramaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteDramaRequest) Reset() {
	*x = DeleteDramaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drama_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDramaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDramaRequest) ProtoMessage() {}

func (x *DeleteDramaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drama_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDramaRequest.ProtoReflect.Descriptor instead.
func (*DeleteDramaRequest) Descriptor() ([]byte, []int) {
	return file_drama_proto_rawDescGZIP(), []int{5}
}

type DeleteDramaReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteDramaReply) Reset() {
	*x = DeleteDramaReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drama_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDramaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDramaReply) ProtoMessage() {}

func (x *DeleteDramaReply) ProtoReflect() protoreflect.Message {
	mi := &file_drama_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDramaReply.ProtoReflect.Descriptor instead.
func (*DeleteDramaReply) Descriptor() ([]byte, []int) {
	return file_drama_proto_rawDescGZIP(), []int{6}
}

type GetDramaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetDramaRequest) Reset() {
	*x = GetDramaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drama_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDramaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDramaRequest) ProtoMessage() {}

func (x *GetDramaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drama_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDramaRequest.ProtoReflect.Descriptor instead.
func (*GetDramaRequest) Descriptor() ([]byte, []int) {
	return file_drama_proto_rawDescGZIP(), []int{7}
}

type GetDramaReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetDramaReply) Reset() {
	*x = GetDramaReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drama_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDramaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDramaReply) ProtoMessage() {}

func (x *GetDramaReply) ProtoReflect() protoreflect.Message {
	mi := &file_drama_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDramaReply.ProtoReflect.Descriptor instead.
func (*GetDramaReply) Descriptor() ([]byte, []int) {
	return file_drama_proto_rawDescGZIP(), []int{8}
}

type ListDramaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListDramaRequest) Reset() {
	*x = ListDramaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drama_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDramaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDramaRequest) ProtoMessage() {}

func (x *ListDramaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drama_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDramaRequest.ProtoReflect.Descriptor instead.
func (*ListDramaRequest) Descriptor() ([]byte, []int) {
	return file_drama_proto_rawDescGZIP(), []int{9}
}

type ListDramaReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*DramaMessage `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *ListDramaReply) Reset() {
	*x = ListDramaReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drama_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDramaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDramaReply) ProtoMessage() {}

func (x *ListDramaReply) ProtoReflect() protoreflect.Message {
	mi := &file_drama_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDramaReply.ProtoReflect.Descriptor instead.
func (*ListDramaReply) Descriptor() ([]byte, []int) {
	return file_drama_proto_rawDescGZIP(), []int{10}
}

func (x *ListDramaReply) GetResults() []*DramaMessage {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_drama_proto protoreflect.FileDescriptor

var file_drama_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x64, 0x72, 0x61, 0x6d, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x61,
	0x70, 0x69, 0x2e, 0x64, 0x72, 0x61, 0x6d, 0x61, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x68, 0x0a, 0x0c, 0x44, 0x72, 0x61,
	0x6d, 0x61, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x22, 0x5e, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x72, 0x61,
	0x6d, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x22, 0x44, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x72, 0x61,
	0x6d, 0x61, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x30, 0x0a, 0x05, 0x64, 0x72, 0x61, 0x6d, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x64, 0x72, 0x61,
	0x6d, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x72, 0x61, 0x6d, 0x61, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x05, 0x64, 0x72, 0x61, 0x6d, 0x61, 0x22, 0x14, 0x0a, 0x12, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x44, 0x72, 0x61, 0x6d, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x12, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x72, 0x61, 0x6d, 0x61, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x14, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x72, 0x61,
	0x6d, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x12, 0x0a, 0x10, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x44, 0x72, 0x61, 0x6d, 0x61, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x11, 0x0a,
	0x0f, 0x47, 0x65, 0x74, 0x44, 0x72, 0x61, 0x6d, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x0f, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x44, 0x72, 0x61, 0x6d, 0x61, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x12, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x72, 0x61, 0x6d, 0x61, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x46, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x72, 0x61,
	0x6d, 0x61, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x34, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x64,
	0x72, 0x61, 0x6d, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x72, 0x61, 0x6d, 0x61, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x32, 0xf9, 0x03,
	0x0a, 0x05, 0x44, 0x72, 0x61, 0x6d, 0x61, 0x12, 0x66, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x44, 0x72, 0x61, 0x6d, 0x61, 0x12, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x64, 0x72, 0x61,
	0x6d, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x72, 0x61, 0x6d,
	0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x64,
	0x72, 0x61, 0x6d, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x72,
	0x61, 0x6d, 0x61, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x15, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0f,
	0x22, 0x0d, 0x2f, 0x64, 0x72, 0x61, 0x6d, 0x61, 0x2f, 0x7b, 0x6e, 0x61, 0x6d, 0x65, 0x7d, 0x12,
	0x66, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x72, 0x61, 0x6d, 0x61, 0x12, 0x20,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x64, 0x72, 0x61, 0x6d, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x44, 0x72, 0x61, 0x6d, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x64, 0x72, 0x61, 0x6d, 0x61, 0x2e, 0x76, 0x31, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x72, 0x61, 0x6d, 0x61, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x15, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0f, 0x1a, 0x0d, 0x2f, 0x64, 0x72, 0x61, 0x6d, 0x61,
	0x2f, 0x7b, 0x6e, 0x61, 0x6d, 0x65, 0x7d, 0x12, 0x66, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x44, 0x72, 0x61, 0x6d, 0x61, 0x12, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x64, 0x72, 0x61,
	0x6d, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x72, 0x61, 0x6d,
	0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x64,
	0x72, 0x61, 0x6d, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x72,
	0x61, 0x6d, 0x61, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x15, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0f,
	0x2a, 0x0d, 0x2f, 0x64, 0x72, 0x61, 0x6d, 0x61, 0x2f, 0x7b, 0x6e, 0x61, 0x6d, 0x65, 0x7d, 0x12,
	0x5d, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x44, 0x72, 0x61, 0x6d, 0x61, 0x12, 0x1d, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x64, 0x72, 0x61, 0x6d, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x72,
	0x61, 0x6d, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x64, 0x72, 0x61, 0x6d, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x72, 0x61,
	0x6d, 0x61, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x15, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0f, 0x12,
	0x0d, 0x2f, 0x64, 0x72, 0x61, 0x6d, 0x61, 0x2f, 0x7b, 0x6e, 0x61, 0x6d, 0x65, 0x7d, 0x12, 0x59,
	0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x72, 0x61, 0x6d, 0x61, 0x12, 0x1e, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x64, 0x72, 0x61, 0x6d, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x44,
	0x72, 0x61, 0x6d, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x64, 0x72, 0x61, 0x6d, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x44,
	0x72, 0x61, 0x6d, 0x61, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x0e, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x08, 0x12, 0x06, 0x2f, 0x64, 0x72, 0x61, 0x6d, 0x61, 0x42, 0x27, 0x0a, 0x0c, 0x61, 0x70, 0x69,
	0x2e, 0x64, 0x72, 0x61, 0x6d, 0x61, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x15, 0x77, 0x65, 0x65,
	0x6b, 0x34, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x72, 0x61, 0x6d, 0x61, 0x2f, 0x76, 0x31, 0x3b,
	0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_drama_proto_rawDescOnce sync.Once
	file_drama_proto_rawDescData = file_drama_proto_rawDesc
)

func file_drama_proto_rawDescGZIP() []byte {
	file_drama_proto_rawDescOnce.Do(func() {
		file_drama_proto_rawDescData = protoimpl.X.CompressGZIP(file_drama_proto_rawDescData)
	})
	return file_drama_proto_rawDescData
}

var file_drama_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_drama_proto_goTypes = []interface{}{
	(*DramaMessage)(nil),       // 0: api.drama.v1.DramaMessage
	(*CreateDramaRequest)(nil), // 1: api.drama.v1.CreateDramaRequest
	(*CreateDramaReply)(nil),   // 2: api.drama.v1.CreateDramaReply
	(*UpdateDramaRequest)(nil), // 3: api.drama.v1.UpdateDramaRequest
	(*UpdateDramaReply)(nil),   // 4: api.drama.v1.UpdateDramaReply
	(*DeleteDramaRequest)(nil), // 5: api.drama.v1.DeleteDramaRequest
	(*DeleteDramaReply)(nil),   // 6: api.drama.v1.DeleteDramaReply
	(*GetDramaRequest)(nil),    // 7: api.drama.v1.GetDramaRequest
	(*GetDramaReply)(nil),      // 8: api.drama.v1.GetDramaReply
	(*ListDramaRequest)(nil),   // 9: api.drama.v1.ListDramaRequest
	(*ListDramaReply)(nil),     // 10: api.drama.v1.ListDramaReply
}
var file_drama_proto_depIdxs = []int32{
	0,  // 0: api.drama.v1.CreateDramaReply.drama:type_name -> api.drama.v1.DramaMessage
	0,  // 1: api.drama.v1.ListDramaReply.results:type_name -> api.drama.v1.DramaMessage
	1,  // 2: api.drama.v1.Drama.CreateDrama:input_type -> api.drama.v1.CreateDramaRequest
	3,  // 3: api.drama.v1.Drama.UpdateDrama:input_type -> api.drama.v1.UpdateDramaRequest
	5,  // 4: api.drama.v1.Drama.DeleteDrama:input_type -> api.drama.v1.DeleteDramaRequest
	7,  // 5: api.drama.v1.Drama.GetDrama:input_type -> api.drama.v1.GetDramaRequest
	9,  // 6: api.drama.v1.Drama.ListDrama:input_type -> api.drama.v1.ListDramaRequest
	2,  // 7: api.drama.v1.Drama.CreateDrama:output_type -> api.drama.v1.CreateDramaReply
	4,  // 8: api.drama.v1.Drama.UpdateDrama:output_type -> api.drama.v1.UpdateDramaReply
	6,  // 9: api.drama.v1.Drama.DeleteDrama:output_type -> api.drama.v1.DeleteDramaReply
	8,  // 10: api.drama.v1.Drama.GetDrama:output_type -> api.drama.v1.GetDramaReply
	10, // 11: api.drama.v1.Drama.ListDrama:output_type -> api.drama.v1.ListDramaReply
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_drama_proto_init() }
func file_drama_proto_init() {
	if File_drama_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_drama_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DramaMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_drama_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDramaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_drama_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDramaReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_drama_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDramaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_drama_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDramaReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_drama_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDramaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_drama_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDramaReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_drama_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDramaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_drama_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDramaReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_drama_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDramaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_drama_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDramaReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_drama_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_drama_proto_goTypes,
		DependencyIndexes: file_drama_proto_depIdxs,
		MessageInfos:      file_drama_proto_msgTypes,
	}.Build()
	File_drama_proto = out.File
	file_drama_proto_rawDesc = nil
	file_drama_proto_goTypes = nil
	file_drama_proto_depIdxs = nil
}
